//! Per-TCP-connection byte counters via the IP Helper "Extended Statistics"
//! API. TCP-only (UDP has no equivalent) and requires collection to be
//! explicitly enabled per-connection before it reports anything, which is
//! why `enable` and `read` are separate steps below.
//!
//! NOTE: the exact type/constant names generated by the `windows` crate for
//! this API surface are sparsely documented upstream and have shifted across
//! crate versions in the past - verify these against the installed
//! `windows` crate docs on a real Windows build before shipping, and adjust
//! field names if the compiler disagrees.

#[cfg(windows)]
pub use win::{enable, read};

#[cfg(windows)]
mod win {
    use windows::Win32::NetworkManagement::IpHelper::{
        GetPerTcpConnectionEStats, SetPerTcpConnectionEStats, MIB_TCPROW_LH,
        TCP_ESTATS_DATA_ROD_v0, TCP_ESTATS_DATA_RW_v0, TcpConnectionEstatsData,
    };

    /// `dwState` lives inside an anonymous union (windows-rs surfaces it as an
    /// opaque `Anonymous` field), and EStats lookups only key off the
    /// local/remote address+port tuple, so the row is zero-initialized rather
    /// than constructed as a literal to avoid depending on that union's
    /// generated type name.
    fn make_row(local_addr: u32, local_port: u16, remote_addr: u32, remote_port: u16) -> MIB_TCPROW_LH {
        let mut row: MIB_TCPROW_LH = unsafe { std::mem::zeroed() };
        row.dwLocalAddr = local_addr;
        row.dwLocalPort = local_port.to_be() as u32;
        row.dwRemoteAddr = remote_addr;
        row.dwRemotePort = remote_port.to_be() as u32;
        row
    }

    /// Turns on Data EStats collection for a connection. Safe to call
    /// repeatedly - once enabled, subsequent calls are a harmless no-op from
    /// the caller's perspective (errors are swallowed).
    ///
    /// The `windows` crate represents the raw (buffer pointer, size) pair from
    /// the C API as a single `&[u8]`/`Option<&mut [u8]>` slice, so the struct
    /// is reinterpreted as bytes rather than passed as a typed pointer.
    pub fn enable(local_addr: u32, local_port: u16, remote_addr: u32, remote_port: u16) {
        let row = make_row(local_addr, local_port, remote_addr, remote_port);
        let rw = TCP_ESTATS_DATA_RW_v0 { EnableCollection: true.into() };
        let rw_bytes = unsafe {
            std::slice::from_raw_parts(&rw as *const _ as *const u8, std::mem::size_of::<TCP_ESTATS_DATA_RW_v0>())
        };
        unsafe {
            let _ = SetPerTcpConnectionEStats(&row, TcpConnectionEstatsData, rw_bytes, 0, 0);
        }
    }

    /// Reads cumulative (bytes_out, bytes_in) for a connection, or `None` if
    /// estats aren't enabled/available for it yet (e.g. just enabled this
    /// tick, or the connection has already closed).
    pub fn read(local_addr: u32, local_port: u16, remote_addr: u32, remote_port: u16) -> Option<(u64, u64)> {
        let row = make_row(local_addr, local_port, remote_addr, remote_port);
        let mut rod = TCP_ESTATS_DATA_ROD_v0::default();
        let rod_bytes = unsafe {
            std::slice::from_raw_parts_mut(&mut rod as *mut _ as *mut u8, std::mem::size_of::<TCP_ESTATS_DATA_ROD_v0>())
        };
        let result = unsafe {
            GetPerTcpConnectionEStats(&row, TcpConnectionEstatsData, None, 0, None, 0, Some(rod_bytes), 0)
        };
        if result != 0 {
            return None;
        }
        Some((rod.DataBytesOut, rod.DataBytesIn))
    }
}

#[cfg(not(windows))]
pub fn enable(_local_addr: u32, _local_port: u16, _remote_addr: u32, _remote_port: u16) {}

#[cfg(not(windows))]
pub fn read(local_addr: u32, local_port: u16, _remote_addr: u32, _remote_port: u16) -> Option<(u64, u64)> {
    use std::time::{SystemTime, UNIX_EPOCH};
    let t = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
    let seed = (local_addr as u64) ^ (local_port as u64);
    Some((t.wrapping_mul(37 + seed % 5), t.wrapping_mul(53 + seed % 7)))
}
